apiVersion: apps/v1
kind: Deployment
metadata:
  name: project2-client-xs90
  labels:
    app: project2-xs90
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project2-xs90
  template:
    metadata:
      labels:
        app: project2-xs90
    spec:
      containers:
      - name: project2-flask-client-xs90
        image: ??????????????
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: quay-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: project2-client-service-xs90
spec:
  selector:
    app: project2-xs90
  ports:
  - port: 62006
    targetPort: 5000