apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pvc-xs90
spec:
  selector:
    matchLabels:
      namespace: xs90
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project2-client-xs90
  labels:
    app: project2-xs90
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project2-xs90
  template:
    metadata:
      labels:
        app: project2-xs90
    spec:
      containers:
      - name: project2-flask-client-xs90
        image: xingyushen/xs90_cli:0.6
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: quay-registry-secret

---
apiVersion: batch/v1
kind: Job
metadata:
  name: project2-xs90-job
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: project2-xs90-playlist-recommender
        image: xingyushen/xs90_rec:0.3
        volumeMounts:
        - mountPath: "/data"
          name: project2-xs90-volume
        env:
        - name: DATASET_URL
          value: "https://homepages.dcc.ufmg.br/~cunha/hosted/cloudcomp-2023s2-datasets/2023_spotify_ds2.csv"
      volumes:
      - name: project2-xs90-volume
        persistentVolumeClaim:
          claimName: project2-pvc-xs90

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-recommender-deployment-xs90
  labels:
    app: song-recommender
spec:
  replicas: 3
  selector:
    matchLabels:
      app: song-recommender
  template:
    metadata:
      labels:
        app: song-recommender
    spec:
      containers:
      - name: song-recommender
        image: xingyushen/xs90_serv:0.3
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /data
          name: project2-xs90-volume
      volumes:
      - name: project2-xs90-volume  # Changed to match the name used in the Job
        persistentVolumeClaim:
          claimName: project2-pvc-xs90  # Changed to match the claim name used in the Job