apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pvc-xs90
spec:
  selector:
    matchLabels:
      namespace: xs90
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
