apiVersion: v1
kind: Service
metadata:
  name: song-recommender-service-xs90
spec:
  selector:
    app: song-recommender
  ports:
    - protocol: TCP
      port: 52006
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: project2-client-service-xs90
spec:
  selector:
    app: project2-xs90
  ports:
  - port: 62006
    targetPort: 5000
